### ISSUE TITLE
Is there a way to get firmware 3.5.3_0047 on viomi v-8(EU)?

### ISSUE THREAD

**Issue by xxTudorxx** [rumpeltux/viomi-rooting#6] opened 2020-07-17 09:31 UTC
I want to get the latest firmware (3.5.3_0047) for multi map support and other improvements, but only the China version(viomi v-7) gets the latest firmware updates and the Europe version(viomi v-8) only has the 3.5.3_0017 update
I really need multi map support since my house has two floors
Also, is there a way to get the no mop zones feature?
![IMG_20200717_133330.jpg](https://user-images.githubusercontent.com/68369199/87777487-3e750d80-c832-11ea-9a54-1e6e61b5b657.jpg)
![IMG_20200717_133303.jpg](https://user-images.githubusercontent.com/68369199/87777543-58aeeb80-c832-11ea-9545-d6c91c097917.jpg)
Here are a few pictures of the vacuum
It was bought from Eastern Europe(Romania) and it is called the Xiaomi Mi Robot Vacuum Mop Pro

**Comment by rumpeltux** [comment] 2020-07-17 11:43
Duplicate of #5

**Closed by rumpeltux** 2020-07-17 11:43 UTC

**Comment by xxTudorxx** [comment] 2020-07-25 09:09
Is there a way to take a backup of my robot before doing anything, and how can I restore that backup?

**Comment by xxTudorxx** [comment] 2020-07-25 09:10
Is there a way to take a backup of the vacuum before flashing and how can I restore the backup if something goes wrong?
