### ISSUE TITLE
Why is the script not installing the latest valetudo?

### ISSUE THREAD

**Issue by w1an** [rumpeltux/viomi-rooting#11] opened 2020-09-24 17:21 UTC
Why is the script installing valetudo 0.5.3? Current version is 0.6.1, sha256 42b27288405db7f6335029c3ffedf8f12971aaf3b8d71ce5c3f28f095926fc76.

Is there a reason for sticking with 0.5.3?

Thanks

**Comment by rumpeltux** [comment] 2020-09-27 10:52
This was a confirmed working version. 0.6.1 is partially broken for viomi. It’s fixed at head, so I’ll update this once a new release is available.

**Comment by mikoladz** [comment] 2020-12-02 20:53
Valetudo 0.5.3 is not working at all with viomi.vacuum.v8, it crashes right away. I have replaced it with 0.6.1 and it's working, although looks like it has limited support for the device.

**Comment by Kaan88** [comment] 2021-02-07 11:55
@rumpeltux Uninstall insructions you are pointing to doesn't have any info about s51valetudo script in rc.d folder. As far as I know your script is using the old method, not the miio_client.

**Comment by rumpeltux** [comment] 2021-02-07 12:29
Yes, deletion just removes the overlay and thereby restores the original firmware version.

For older uninstall instructions, refer to the respective version, e.g. https://github.com/Hypfer/Valetudo/blob/0.5.3/docs/_pages/installation/viomi.md

**Comment by forast3r** [comment] 2021-03-26 11:38
Just a quick note on the rooting script, as far as I have seen, it installs an older version of valetudo, note that this old version has some missing line(s). For example in /etc/init.d/valetudo (source: Valetudo/deployment/viomi/etc/init.d/valetudo)

        procd_open_instance
missing ->>>	procd_set_param env VALETUDO_CONFIG_PATH=/mnt/UDISK/valetudo_config.json
	procd_set_param oom_adj $OOM_ADJ

otherwise, the config file won't survive a reboot

**Comment by rumpeltux** [comment] 2021-04-07 18:52
Fixed with #24

**Closed by rumpeltux** 2021-04-07 18:52 UTC
