### ISSUE TITLE
Valetudo does not start with the startup script

### ISSUE THREAD

**Issue by mikoladz** [rumpeltux/viomi-rooting#15] opened 2020-12-02 20:59 UTC
I have rooted viomi.vacuum.v8 with the great viomi-rooting.sh script, however there were some issues. One was #13 easy to fix. The other one is that the "/etc/init.d/valetudo start" does not start valetudo. The script goes as this:

#!/bin/sh /etc/rc.common
START=97
STOP=99
USE_PROCD=1
PROG=/mnt/UDISK/valetudo
OOM_ADJ=-17
start_service() {
  procd_open_instance
  procd_set_param oom_adj $OOM_ADJ
  procd_set_param command $PROG
  procd_set_param stdout 1 # forward stdout of the command to logd
  procd_set_param stderr 1 # same for stderr
  procd_close_instance
}
shutdown() {
  echo shutdown
}

Running "/mnt/UDISK/valetudo" is working as expected.
Is there anything wrong with the script?

**Comment by rumpeltux** [comment] 2020-12-06 10:01
No script looks fine. Not sure what this issue is.

I’ll close it as I can’t help, but if you do figure out the root cause, let me know. Thanks!

**Closed by rumpeltux** 2020-12-06 10:01 UTC

**Comment by mikoladz** [comment] 2020-12-07 21:06
I don't know what happened. After a reboot of the device the script started valetudo. I did not change anything. It is probably this magic behind a reboot. :-)
